// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import BaseButton from './components/BaseButton.vue'
import HelloA from './components/HelloA.vue'
import HelloB from './components/HelloB.vue'

// Export components individually
export { BaseButton, HelloA, HelloB }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('BaseButton', BaseButton)
  Vue.component('HelloA', HelloA)
  Vue.component('HelloB', HelloB)
}

// Export the library as a plugin
export default { install: install }
